# NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [1]:
import numpy as np

#### Create an array of 10 zeros 

In [5]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [6]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [7]:
5*np.ones(10)

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Create an array of the integers from 10 to 50

In [12]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

In [13]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [14]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [15]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [16]:
np.random.rand()

0.10121151338241474

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [17]:
np.random.rand(25)

array([0.60244606, 0.50823448, 0.41825586, 0.76972405, 0.098314  ,
       0.72123614, 0.03905991, 0.91867221, 0.1696146 , 0.92440854,
       0.81066945, 0.02394735, 0.26054313, 0.30706709, 0.40236277,
       0.72441757, 0.98910853, 0.82835513, 0.03715406, 0.95186913,
       0.76654829, 0.59546403, 0.65565924, 0.31788644, 0.13657985])

#### Create the following matrix:

In [29]:
np.random.random_sample((10,10))

array([[0.31637131, 0.75458389, 0.95066603, 0.52613868, 0.25930927,
        0.69756482, 0.893147  , 0.90089486, 0.71739112, 0.22927648],
       [0.32852982, 0.49104289, 0.24908593, 0.64298089, 0.71064754,
        0.89403603, 0.87062297, 0.80642856, 0.21614556, 0.81009275],
       [0.12396199, 0.16111107, 0.55371172, 0.00294866, 0.89067962,
        0.70993795, 0.37019716, 0.86163049, 0.69148671, 0.65707198],
       [0.84754394, 0.33589221, 0.42200851, 0.28008705, 0.59891187,
        0.33806158, 0.488792  , 0.08048686, 0.29693478, 0.35217824],
       [0.08018263, 0.35166762, 0.42793349, 0.49237074, 0.08391424,
        0.36603305, 0.73823476, 0.08142366, 0.84458001, 0.16892976],
       [0.7444015 , 0.54028318, 0.00486122, 0.36277111, 0.33492509,
        0.91882215, 0.24273826, 0.5543339 , 0.4622517 , 0.44062351],
       [0.60580987, 0.74550134, 0.99037723, 0.00156506, 0.35290654,
        0.70728921, 0.23816088, 0.08807409, 0.32589641, 0.02971032],
       [0.79973055, 0.95764142, 0.2639918

#### Create an array of 20 linearly spaced points between 0 and 1:

In [26]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [30]:
matrix = np.arange(1,26).reshape(5,5)
matrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [39]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [33]:
matrix[0:,1:]

array([[ 2,  3,  4,  5],
       [ 7,  8,  9, 10],
       [12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [37]:
matrix[3,4]

20

In [30]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [43]:
matrix[0:3, 1:2]

array([[ 2],
       [ 7],
       [12]])

In [31]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [44]:
matrix[4:]

array([[21, 22, 23, 24, 25]])

In [32]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [45]:
matrix[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [46]:
np.sum(matrix)

325

#### Get the standard deviation of the values in mat

In [49]:
np.std(matrix)

7.211102550927978

#### Get the sum of all the columns in mat

In [48]:
np.sum(matrix, axis=0)

array([55, 60, 65, 70, 75])

# Great Job!